lint:
  actions_ci: false
nf_core_version: 3.1.2
repository_type: pipeline
template:
  author: kuebra.narci@dkfz.de
  description: "Benchmarking pipeline for germline and somatic variant callers "
  force: false
  is_nfcore: true
  name: variantbenchmarking
  org: nf-core
  outdir: .
  version: 1.0dev
